// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {BabyJubJub} from "@taceo/babyjubjub/BabyJubJub.sol";
import {OprfKeyGen} from "./OprfKeyGen.sol";

uint256 constant PUBLIC_INPUT_LENGTH_KEYGEN_13 = 24;
uint256 constant PUBLIC_INPUT_LENGTH_KEYGEN_25 = 36;

interface IVerifierKeyGen13 {
    function verifyCompressedProof(
        uint256[4] calldata compressedProof,
        uint256[PUBLIC_INPUT_LENGTH_KEYGEN_13] calldata input
    ) external view;
}

interface IVerifierKeyGen25 {
    function verifyCompressedProof(
        uint256[4] calldata compressedProof,
        uint256[PUBLIC_INPUT_LENGTH_KEYGEN_25] calldata input
    ) external view;
}

interface IOprfKeyRegistry {
    // ==================================
    //              EVENTS
    // ==================================

    /// @notice Emitted when a peer's Round 1/2/3 contribution for a key-gen or reshare is registered.
    /// @param oprfKeyId The unique identifier for the OPRF key process.
    /// @param partyId The party ID of the contributing peer.
    /// @param round The round number this confirmation is for (1, 2, or 3).
    /// @param epoch The reshare epoch, or 0 if this is the initial key-gen.
    event KeyGenConfirmation(uint160 indexed oprfKeyId, uint16 indexed partyId, uint8 round, uint32 epoch);

    /// @notice Emitted when `initKeyGen` starts a new key-generation process, signaling peers to submit Round 1 contributions.
    /// @param oprfKeyId The unique identifier for the OPRF key process.
    /// @param threshold The threshold number of producers required for this key-gen.
    event SecretGenRound1(uint160 indexed oprfKeyId, uint256 threshold);

    /// @notice Emitted once all peers have submitted Round 1 for a key-gen, signaling producers to submit Round 2.
    /// @param oprfKeyId The unique identifier for the OPRF key process.
    /// @param epoch The epoch: 0 for the initial key-gen, or the new reshare epoch during a reshare.
    event SecretGenRound2(uint160 indexed oprfKeyId, uint32 indexed epoch);

    /// @notice Emitted once enough producers have submitted Round 2 for a key-gen, signaling all peers to submit Round 3.
    /// @param oprfKeyId The unique identifier for the OPRF key process.
    event SecretGenRound3(uint160 indexed oprfKeyId);

    /// @notice Emitted once all peers have submitted Round 3, finalizing the OPRF public-key registration.
    /// @param oprfKeyId The unique identifier for the OPRF key process.
    /// @param epoch The epoch of the key that was just finalized (0 for the initial key-gen).
    event SecretGenFinalize(uint160 indexed oprfKeyId, uint32 indexed epoch);

    /// @notice Emitted when `initReshare` starts a reshare process, signaling peers to submit Round 1 contributions.
    /// @param oprfKeyId The unique identifier for the OPRF key process.
    /// @param threshold The threshold number of producers required for this reshare.
    /// @param epoch The new epoch being generated by this reshare.
    event ReshareRound1(uint160 indexed oprfKeyId, uint256 threshold, uint32 indexed epoch);

    /// @notice Emitted once enough producers have submitted Round 2 for a reshare, signaling all peers to submit Round 3.
    /// @param oprfKeyId The unique identifier for the OPRF key process.
    /// @param lagrange The Lagrange coefficients computed for the producing parties, needed by peers to decrypt Round 2 ciphertexts.
    /// @param epoch The new epoch being generated by this reshare.
    event ReshareRound3(uint160 indexed oprfKeyId, uint256[] lagrange, uint32 indexed epoch);

    /// @notice Emitted when `deleteOprfPublicKey` deletes a registered OPRF public-key and its state.
    /// @param oprfKeyId The unique identifier for the OPRF key process.
    event KeyDeletion(uint160 indexed oprfKeyId);

    /// @notice Emitted when `abortKeyGen` aborts an in-progress key-generation or reshare process.
    /// @param oprfKeyId The unique identifier for the OPRF key process.
    event KeyGenAbort(uint160 indexed oprfKeyId);

    /// @notice Emitted when `revokeKeyGenAdmin` removes an address's key-generation admin permissions.
    /// @param admin The admin address that was revoked.
    event KeyGenAdminRevoked(address indexed admin);

    /// @notice Emitted when `addKeyGenAdmin` grants an address key-generation admin permissions.
    /// @param admin The admin address that was registered.
    event KeyGenAdminRegistered(address indexed admin);

    /// @notice Emitted when Round 1 completes without enough producers to proceed; the key-gen/reshare is left `STUCK` until an admin intervenes (e.g. via `abortKeyGen`).
    /// @param oprfKeyId The unique identifier for the OPRF key process.
    event NotEnoughProducers(uint160 indexed oprfKeyId);

    /// @notice Emitted when `changeVerifierContract` updates the key-generation Groth16 verifier contract.
    /// @param oldContract The address of the previous verifier contract.
    /// @param newContract The address of the new verifier contract.
    event VerifierContractChanged(address indexed oldContract, address indexed newContract);

    /// @notice Emitted for each peer slot when `registerOprfPeers` changes the address occupying that party ID.
    /// @param partyId The party ID whose peer address changed.
    /// @param oldPeer The previous address for this party ID, or the zero address if this is the first registration.
    /// @param newPeer The new address for this party ID.
    event OprfPeerChanged(uint16 indexed partyId, address indexed oldPeer, address indexed newPeer);

    // ==================================
    //              ERRORS
    // ==================================

    /// @notice Thrown when a peer submits a second contribution for a round they already submitted for.
    error AlreadySubmitted();

    /// @notice Thrown when a submitted contribution fails validation (e.g. an invalid or off-curve BabyJubJub point, a zero commitment, or an inconsistent producer/consumer choice).
    error BadContribution();

    /// @notice Thrown when an operation targets an `oprfKeyId` whose key-gen/reshare state has been deleted.
    /// @param id The OPRF key identifier that was deleted.
    error DeletedId(uint160 id);

    /// @notice Thrown when a proxy call is made before the implementation has been initialized.
    error ImplementationNotInitialized();

    /// @notice Thrown when `revokeKeyGenAdmin` would remove the last remaining key-generation admin.
    error LastAdmin();

    /// @notice Thrown when the caller is not a registered OPRF peer.
    error NotAParticipant();

    /// @notice Thrown when the contract has not yet completed `registerOprfPeers` (i.e. `isContractReady` is false).
    error NotReady();

    /// @notice Thrown when the caller is not a key-generation admin (or, where applicable, the owner).
    error OnlyAdmin();

    /// @notice Thrown when `registerOprfPeers` is called with duplicate addresses.
    error PartiesNotDistinct();

    /// @notice Thrown when `registerOprfPeers` is called with a different number of addresses than `numPeers`.
    /// @param expectedParties The expected number of peer addresses (`numPeers`).
    error UnexpectedAmountPeers(uint256 expectedParties);

    /// @notice Thrown when an operation references an `oprfKeyId` that has no registered public-key.
    /// @param id The OPRF key identifier that is unknown.
    error UnknownId(uint160 id);

    /// @notice Thrown when a Round 2 contribution is submitted for a `numPeers`/`threshold` combination that has no corresponding verifier circuit.
    error UnsupportedNumPeersThreshold();

    /// @notice Thrown when a contribution is submitted while the key-gen/reshare process is not in the round that accepts it.
    /// @param round The round the process is actually in.
    error WrongRound(OprfKeyGen.Round round);

    // ==================================
    //         ADMIN FUNCTIONS
    // ==================================

    /// @notice Revokes an admin's key-generation permissions.
    ///
    /// @dev This function is intended as an emergency measure (e.g. key loss).
    /// In the future, revocation should require threshold authentication.
    /// Currently, any admin may revoke another admin, meaning a single admin
    /// can remove all others except the last remaining one.
    ///
    /// @param _keygenAdmin The admin address to revoke
    function revokeKeyGenAdmin(address _keygenAdmin) external;

    /// @notice Updates the key generation verifier contract.
    ///
    /// @dev This function does not verify whether the provided address is a valid
    /// or trusted key generation verifier contract. Use with caution.
    ///
    /// @param newKeyGenVerifier The address of the new verifier contract
    function changeVerifierContract(address newKeyGenVerifier) external;

    /// @notice Grants key-generation admin permissions to an address.
    ///
    /// @dev In the future, adding admins should require threshold authentication.
    /// Currently, any existing admin may add another admin.
    ///
    /// @param _keygenAdmin The admin address to register
    function addKeyGenAdmin(address _keygenAdmin) external;

    /// @notice Registers the OPRF peers with their addresses and assigns party IDs.
    /// Can only be called by the contract owner. Re-registering requires that
    /// existing peers keep their party ID.
    ///
    /// @dev Ensures the number of addresses matches `numPeers` and that all addresses are distinct.
    /// Deletes any previous peer registrations and initializes the new ones. Sets
    /// `isContractReady` to true once registration completes.
    ///
    /// @param _peerAddresses An array of OPRF peer addresses to register.
    function registerOprfPeers(address[] calldata _peerAddresses) external;

    /// @notice Initializes a new key-generation process with the given OPRF key ID.
    /// Reverts if the identifier is zero, already used, or deleted.
    ///
    /// @dev Uses the provided `oprfKeyId` as the unique identifier. Checks storage
    /// to prevent resubmission or re-initialization. Emits the Round1 event upon success.
    ///
    /// @param oprfKeyId The unique identifier for the OPRF public key.
    function initKeyGen(uint160 oprfKeyId) external;

    /// @notice Initializes a reshare process for a given OPRF key ID.
    /// Can be used to re-randomize MPC shares, replace parties, or regenerate shares
    /// if a node loses access. Reuses the previous state but clears old key-generation data.
    ///
    /// @dev Checks that the key ID exists and is not deleted. Prevents resubmission if
    /// the reshare is already started. Initializes the reshare state and increments the epoch.
    /// Emits the Round1 event upon success.
    ///
    /// @param oprfKeyId The unique identifier for the OPRF public key.
    function initReshare(uint160 oprfKeyId) external;

    /// @notice Deletes an OPRF public key and all associated state.
    /// Can only delete keys that exist and are not currently in a key-generation or reshare process.
    /// If a process is stuck, call `abortKeyGen` first before deleting.
    ///
    /// @dev Clears both the registered public key and the running key-gen state.
    /// Emits `KeyDeletion` upon success.
    ///
    /// @param oprfKeyId The unique identifier for the OPRF public key.
    function deleteOprfPublicKey(uint160 oprfKeyId) external;

    /// @notice Aborts an in-progress OPRF key-generation or reshare process.
    /// Call `initKeyGen` or `initReshare` afterwards to restart the process if needed.
    ///
    /// @dev Resets the key-gen state to allow for a fresh start. Emits `KeyGenAbort`.
    ///
    /// @param oprfKeyId The unique identifier for the OPRF public key.
    function abortKeyGen(uint160 oprfKeyId) external;

    // ==================================
    //        OPRF Peer FUNCTIONS
    // ==================================

    /// @notice Adds a Round 1 contribution to the key generation process. Only callable by registered OPRF peers.
    /// @param oprfKeyId The unique identifier for the key-gen.
    /// @param data The Round 1 contribution data. See `OprfKeyGen.Round1Contribution` for details.
    function addRound1KeyGenContribution(uint160 oprfKeyId, OprfKeyGen.Round1Contribution calldata data) external;

    /// @notice Adds a Round 1 contribution to the re-sharing process. Only callable by registered OPRF peers. This method does some more work than the basic key-gen.
    /// We need threshold many PRODUCERS, meaning those will do the re-sharing. Nevertheless, all other parties need to participate as CONSUMERS and provide an ephemeral public-key so that the producers can create the new shares for them, so at least round 1 needs contributions by all nodes.
    ///
    /// @param oprfKeyId The unique identifier for the key-gen.
    /// @param data The Round 1 contribution data. See `OprfKeyGen.Round1Contribution` for details.
    function addRound1ReshareContribution(uint160 oprfKeyId, OprfKeyGen.Round1Contribution calldata data) external;

    /// @notice Adds a Round 2 contribution to the key generation process. Only callable by registered OPRF peers. Is the same for key-gen and reshare, with the small difference with how the commitments for next reshare are computed and that we need less producers for reshare.
    ///
    /// @param oprfKeyId The unique identifier for the key-gen.
    /// @param data The Round 2 contribution data. See `OprfKeyGen.Round2Contribution` for details.
    /// @dev This internally verifies the Groth16 proof provided in the contribution data to ensure it is constructed correctly.
    function addRound2Contribution(uint160 oprfKeyId, OprfKeyGen.Round2Contribution calldata data) external;

    /// @notice Adds a Round 3 contribution to the key generation process. Only callable by registered OPRF peers. This is exactly the same process for key-gen and reshare because nodes just acknowledge that they received their ciphertexts.
    ///
    /// @param oprfKeyId The unique identifier for the OPRF public-key.
    /// @dev This does not require any calldata, as it is simply an acknowledgment from the peer that is is done.
    function addRound3Contribution(uint160 oprfKeyId) external;

    // ==================================
    //           HELPER FUNCTIONS
    // ==================================

    /// @notice Checks if the caller is a registered OPRF participant and returns their party ID.
    /// @return The party ID of the given participant if they are a registered participant.
    function getPartyIdForParticipant(address participant) external view returns (uint256);

    /// @notice Checks if the caller is a registered OPRF participant and returns ALL the ephemeral public keys created in round 1 of the key gen identified by the provided oprfKeyId. This method will be called by the nodes during round 2. The producers will receive all ephemeral public keys in order to encrypt the recreated shares (of the shares). The consumers will receive an empty array - this signals them that they don't need to participate in this round and just wait until the producers are done with this round.
    /// @param oprfKeyId The unique identifier for the OPRF public-key.
    /// @return The ephemeral public keys generated in round 1 iff a producer. An empty array iff a consumer.
    function loadPeerPublicKeysForProducers(uint160 oprfKeyId) external view returns (BabyJubJub.Affine[] memory);

    /// @notice Checks if the caller is a registered OPRF participant and returns only the ephemeral public OF THE PRODUCERS. The producers encrypted all shares in the previous round with DHE, therefore the recipients need the producer's public-key. For simplicity, the producers also call this method to receive the public-keys (including their own).
    /// @param oprfKeyId The unique identifier for the OPRF public-key.
    /// @return The ephemeral public keys OF THE PRODUCERS generated in round 1
    function loadPeerPublicKeysForConsumers(uint160 oprfKeyId) external view returns (BabyJubJub.Affine[] memory);

    /// @notice Checks if the caller is a registered OPRF participant and returns their Round 2 ciphertexts for the specified key-gen.
    /// @param oprfKeyId The unique identifier for the OPRF public-key.
    /// @return An array of Round 2 ciphertexts belonging to the caller.
    function checkIsParticipantAndReturnRound2Ciphers(uint160 oprfKeyId)
        external
        view
        returns (OprfKeyGen.SecretGenCiphertext[] memory);

    /// @notice Retrieves the specified OPRF public-key.
    /// @param oprfKeyId The unique identifier for the OPRF public-key.
    /// @return The BabyJubJub element representing the nullifier public key.
    function getOprfPublicKey(uint160 oprfKeyId) external view returns (BabyJubJub.Affine memory);

    /// @notice Retrieves the specified OPRF public-key along with its current epoch.
    /// @param oprfKeyId The unique identifier for the OPRF public-key.
    /// @return The BabyJubJub element representing the nullifier public key and the current epoch.
    function getOprfPublicKeyAndEpoch(uint160 oprfKeyId)
        external
        view
        returns (OprfKeyGen.RegisteredOprfPublicKey memory);

    // ==================================
    //           STATE GETTERS
    // ==================================

    /// @notice Whether the contract is ready (i.e. `registerOprfPeers` has completed).
    function isContractReady() external view returns (bool);

    /// @notice Returns whether the given address is a key-generation admin.
    function keygenAdmins(address admin) external view returns (bool);

    /// @notice The number of registered key-generation admins.
    function amountKeygenAdmins() external view returns (uint256);

    /// @notice The address of the current key-generation Groth16 verifier contract.
    function keyGenVerifier() external view returns (address);

    /// @notice The threshold number of producers required for key-gen/reshare.
    function threshold() external view returns (uint16);

    /// @notice The total number of OPRF peers.
    function numPeers() external view returns (uint16);

    /// @notice The registered peer address at the given index (indices `0..numPeers-1`).
    function peerAddresses(uint256 index) external view returns (address);
}
